AllCops:
  TargetRubyVersion: 2.6

Layout/AlignHash:
  EnforcedColonStyle: table
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
